site_name: tiSPHi
nav:
    - Home: index.md
    - Basic knowledge: math.md
    - SPH foundations: foundation.md
    - SPH for fluid: fluid.md
    - SPH for soil: soil.md
    - Code frame: codeframe.md
    - About: about.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
